Repository woowa-techcamp-2020/bmart-1, pull requests merged in 2020-08, with the labels that each got.

#76 Slot machine 구현 및 리팩토링 계획
  src/components/SlotMachine/index.tsx
  src/components/SlotMachine/style.scss
  src/stories/SlotMachine.stories.tsx
Labels: WIP

#115 Category menu component
  src/assets/images/categories/avocado.png
  src/assets/images/categories/bread.png
  src/assets/images/categories/dish.png
  src/assets/images/categories/fish.png
  src/assets/images/categories/hongsam.png
  src/assets/images/categories/perfume.png
  src/assets/images/categories/pets.png
  src/assets/images/categories/refrigerator.png
  src/assets/images/categories/rubberduck.png
  src/assets/images/categories/salad.png
  src/assets/images/categories/sauce.png
  src/assets/images/categories/shelf.png
  src/components/Carousel/AdBannerContainer/index.tsx
  src/components/CategoryItem/index.tsx
  src/components/CategoryItem/style.scss
  src/pages/Bmart/Home/index.tsx
  src/pages/Bmart/Home/style.scss
  src/pages/Bmart/SlidePage/style.scss
  src/styles/base.scss
Labels: Enhancement, React Component

#124 refactor: convert SearchResults into ProductContainer
  src/components/ProductContainer/index.tsx
  src/components/ProductContainer/style.scss
  src/components/Search/index.tsx
Labels: React Component

#129 Custom Dialog + Design System Update
  src/styles/base.scss
  src/utils/dialog/index.ts
  src/utils/dialog/style.scss
Labels: Documentation
